### PR TITLE
chore: Reformat code with Black

### PR DESCRIPTION
**Pull request by RDIL**
Reformats the codebase with [Black](https://github.com/psf/black), a formatter that is based on PEP8, and makes code look nice!  

Signed-off-by: Reece Dunham <me@rdil.rocks>

### CODE REVIEW

**Comment by agronholm** [comment]
I'm going to have to reject this because I hate black with a passion. Sorry.

**Comment by RDIL** [comment]
I'm fine with that, but just out of curiosity, what do you hate about black?

**Comment by agronholm** [comment]
The various choices in code styling that, from my perspective, reduce legibility of the code.

**Comment by RDIL** [comment]
Okay, I'll revert the Black changes - will you accept the minor-fixups part of the PR if I do?

**Comment by agronholm** [comment]
What minor fixups are you talking about?

**Comment by agronholm** [comment]
If you have fixes to the code, please open another PR. They should be dealt with as a separate issue.

**Comment by RDIL** [comment]
Okay.

**Comment by RDIL** [comment]
Opened #351.

**Comment by agronholm** [comment]
I've come around regarding this issue and have reformatted the code base in `black`. All the other PyPA repos use `black` too so I figured I'd follow suit.

**Pull request closed without merging**
