### PR TITLE
Make license auto-detectable by GitHub

### PR DESCRIPTION
**Pull request by di**
This aligns wheel's license with [GitHub's MIT license template](https://github.com/licenses/license-templates/blob/master/templates/mit.txt) and moves it to [a filename that GitHub supports](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) so GitHub is able to auto-detect this repository as having a MIT license.

### CODE REVIEW

**Comment by SpecLad** [comment]
FWIW, I think GitHub can locate the license at its current filename, since if you open https://github.com/pypa/wheel, there's a "View license" link in the sidebar. It just needs to be aligned with the template.

**Comment by agronholm** [comment]
> FWIW, I think GitHub can locate the license at its current filename, since if you open https://github.com/pypa/wheel, there's a "View license" link in the sidebar. It just needs to be aligned with the template.

I concur. Pip uses the same file name for the license. So @di , please change the file name back to the original one. I'm willing to merge this then.

**Comment by SpecLad** [comment]
Also, the only lines that need to be corrected are the first two ("MIT License" and "Copyright"). The tool GitHub uses to detect licenses ([licensee](https://github.com/licensee/licensee)) ignores whitespace, so reformatting the paragraphs is unnecessary.

**Comment by di** [comment]
Done, thanks @SpecLad!

**Comment by agronholm** [comment]
Thanks!

**Pull request merged**
