### PR TITLE
Apply ruff/flake8-implicit-str-concat rule ISC001

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
https://docs.astral.sh/ruff/rules/single-line-implicit-string-concatenation/

### CODE REVIEW

**Comment by agronholm** [comment]
I think what would be best is to actually add the relevant `ruff` rule to `pyproject.toml` and then let nature take its course.

**Comment by DimitriPapadopoulos** [comment]
It is not compatible with `ruff format` (yet):
https://github.com/astral-sh/ruff/issues/8272

**Comment by agronholm** [comment]
In the link issue, this is discussed and, as far as I could understand, ISC001 is not actually incompatible with the formatter.

**Comment by DimitriPapadopoulos** [comment]
It's in the [conflict list](https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules).

**Comment by DimitriPapadopoulos** [comment]
I could change:
https://github.com/pypa/wheel/blob/376373b9690e746c36e3984808759e9c32d5e014/.pre-commit-config.yaml#L20-L25
into:
```yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.3
  hooks:
    - id: ruff
      args: [--fix, --show-fixes]
    - id: ruff-format
    - id: ruff
      args: [ --select, ISC001, --fix, --show-fixes ]

**Comment by agronholm** [comment]
Actually I now have a sweeping change commit locally that would do all this, and more.

**Comment by agronholm** [comment]
These sweeping changes covered all of the changes here, so I'm closing this PR as no longer necessary. Thanks for bringing this up!

**Comment by DimitriPapadopoulos** [comment]
Now I get this warning whenever running ruff:
```console
$ ruff format
warning: The following rules may cause conflicts when used with the formatter: `ISC001`. To avoid unexpected behavior, we recommend disabling these rules, either by removing them from the `select` or `extend-select` configuration, or adding them to the `ignore` configuration.
54 files left unchanged
$ 
```

**Pull request closed without merging**
