### PR TITLE
Add configuration for Flake8.

### PR DESCRIPTION
**Pull request by HexDecimal**
The main differences from the defaults are enabling the opinionated bugbear codes and excluding the vendored sources.

### CODE REVIEW

**Comment by agronholm** [comment]
Flake8 was meant to be run through `pre-commit` which already excludes the vendored sources.

**Comment by HexDecimal** [comment]
I sometimes run it manually and it flags the vendored files when I do.

**Comment by agronholm** [comment]
So, don't? Running `flake8` manually only runs the flake8 checks and not the rest of the checks that need to pass for CI to pass. Just instead of `flake8`, run `pre-commit run -a flake8` if you only want to run flake8 checks.

**Comment by agronholm** [comment]
What makes this even more important is that, once I can, I will switch from the official flake8 to `pyproject-flake8` so I can ditch `setup.cfg` entirely.

**Comment by HexDecimal** [comment]
I mean things like the `--max-complexity` option are reasonable to be checked on manually.

**Comment by agronholm** [comment]
Aside from the vendor exclusion, what's the rationale for these specific settings?

**Comment by HexDecimal** [comment]
Git checks out files with CLRF on Windows, so I can't install the pre commit hooks unless I branch off of #474.

**Comment by HexDecimal** [comment]
> Aside from the vendor exclusion, what's the rationale for these specific settings?

`select = B,B9,E,F,C9` mostly copied from the default settings from the Flake8 docs.  `W` is excluded since Black handles those issues.  `B9` enables the extra bugbear codes which already pass, `B` enables the usual bugbear codes.
https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-select

`extend-ignore = E203` required for Black or else you can't have math in square brackets.  Using `extend-ignore` will not replace the default commonly ignored codes which would conflict with Black.

**Comment by henryiii** [comment]
This is now closable, as Ruff is used instead of flake8.

**Pull request closed without merging**
