### PR TITLE
Make wheelfile a stand-alone module to simplify vendoring

### PR DESCRIPTION
**Pull request by FRidh**
https://github.com/pypa/wheel/issues/262 proposes a public API for the wheel package. That's a good thing to reduce duplication and facilitate reuse. I would expect it to be primarily used by build systems such as setuptools, flit, enscons, mesonpep517, ...

However, bootstrapping of build systems that have external dependencies is often problematic (https://github.com/pypa/setuptools/issues/980). The core of this package is the `wheelfile` module. Let's make it so that others can easily vendor this now stand-alone module.

### CODE REVIEW

**Comment by agronholm** [comment]
Do you have a specific project you want to vendor this module to? Also, wouldn't it be prudent to decide the public API first?

**Comment by FRidh** [comment]
> Do you have a specific project you want to vendor this module to?

I am experimenting currently with a PEP 517 [back-end that could support multiple systems](https://discuss.python.org/t/how-do-we-get-out-of-the-business-of-driving-c-compilers/2591/5), such as meson, cmake and scons.

So far I am fine using my fork, so no need to get it in.

> Also, wouldn't it be prudent to decide the public API first?

Maybe. See it as a first step. At this point, it is not fixed yet. But this module (`wheelfile`) is the most important one, although I'll probably reuse `pep425tags` as well.

**Comment by dholth** [comment]
Here are a couple of other wheel manifest generators to compare.

https://bitbucket.org/dholth/sdl2_lib/src/66225dd8dc2d77ba21c6e7b1938b9a70116bb18e/wscript#lines-65

https://bitbucket.org/dholth/enscons/src/263d0525b891172763c7926fb866c518907e37cc/enscons/__init__.py#lines-233

**Comment by agronholm** [comment]
I will probably end up rejecting this due to the major refactoring I'm doing in the publicapi branch.

**Comment by agronholm** [comment]
Yeah, you will find that the new wheelfile module in the `publicapi` branch is quite self contained.

**Pull request closed without merging**
