### PR TITLE
Simplify Unicode handling in metadata.py

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by agronholm** [comment]
I never quite understood this part of the wheel codebase. But `str(pkg_info['Description'])` will raise `UnicodeEncodeError` on Python 2 if there are non-ASCII characters in the description, won't it?

**Comment by jdufresne** [comment]
Nope, it won't. At least not with the code as it exists today. On Python 2, the `pkg_info` is already read as an ascii `str`, nevear `unicode`. The code for this is here:

https://github.com/pypa/wheel/blob/0036f80513457a95a309c81d8a63f113b52dbafa/src/wheel/pkginfo.py#L34-L39

The `str()` call only affects Python 3 to handle type `email.header.Header`.

Tests already exist for this:

```
tests/testdata/complex-dist/setup.py
5          description=u'Another testing distribution \N{SNOWMAN}',
6          long_description=u'Another testing distribution \N{SNOWMAN}',

tests/testdata/extension.dist/setup.py
5          description=u'A testing distribution \N{SNOWMAN}',

tests/testdata/abi3extension.dist/setup.py
5          description=u'A testing distribution \N{SNOWMAN}',

tests/testdata/unicode.dist/setup.py
6          description=u'A testing distribution \N{SNOWMAN}',

tests/testdata/simple.dist/setup.py
5          description=u'A testing distribution \N{SNOWMAN}',
```

**Comment by agronholm** [comment]
I think I'll defer this until I drop Python 2 support (which should be soon, though).

**Comment by agronholm** [comment]
I'm wondering: is there any reason at all for using surrogates? Can we not rely on the pkg-info being utf-8 encoded?

**Comment by jdufresne** [comment]
With some testing, it appears not. Here are the test failures with the following diff:

```diff
diff --git a/src/wheel/metadata.py b/src/wheel/metadata.py
index be3a2c1..9cc0f28 100644
--- a/src/wheel/metadata.py
+++ b/src/wheel/metadata.py
@@ -106,9 +106,4 @@ def dedent_description(pkg_info):
          textwrap.dedent('\n'.join(description_lines[1:])),
          '\n'))
 
-    if sys.version_info.major >= 3:
-        description_dedent = description_dedent \
-            .encode("utf8") \
-            .decode("ascii", "surrogateescape")
-
     return description_dedent
```

```
$ tox -e py38
GLOB sdist-make: /home/jon/devel/wheel/setup.py
py38 create: /home/jon/devel/wheel/.tox/py38
py38 inst: /home/jon/devel/wheel/.tox/.tmp/package/1/wheel-0.34.2.zip
py38 installed: attrs==19.3.0,coverage==5.1,more-itertools==8.3.0,packaging==20.4,pluggy==0.13.1,py==1.8.1,pyparsing==2.4.7,pytest==5.4.3,pytest-cov==2.10.0,six==1.15.0,wcwidth==0.2.4
py38 run-test-pre: PYTHONHASHSEED='135263917'
py38 run-test: commands[0] | /home/jon/devel/wheel/.tox/py38/bin/python -b -m pytest -W always
==================================================================================================================================================== test session starts =====================================================================================================================================================
platform linux -- Python 3.8.3, pytest-5.4.3, py-1.8.1, pluggy-0.13.1
cachedir: .tox/py38/.pytest_cache
rootdir: /home/jon/devel/wheel, inifile: setup.cfg, testpaths: tests
plugins: cov-2.10.0
collected 59 items                                                                                                                                                                                                                                                                                                           

tests/test_bdist_wheel.py EE.........                                                                                                                                                                                                                                                                                  [ 18%]
tests/test_macosx_libfile.py .........                                                                                                                                                                                                                                                                                 [ 33%]
tests/test_metadata.py .                                                                                                                                                                                                                                                                                               [ 35%]
tests/test_pkginfo.py .                                                                                                                                                                                                                                                                                                [ 37%]
tests/test_tagopt.py .........s.s                                                                                                                                                                                                                                                                                      [ 57%]
tests/test_wheelfile.py ..................                                                                                                                                                                                                                                                                             [ 88%]
tests/cli/test_convert.py .E                                                                                                                                                                                                                                                                                           [ 91%]
tests/cli/test_pack.py ....                                                                                                                                                                                                                                                                                            [ 98%]
tests/cli/test_unpack.py E                                                                                                                                                                                                                                                                                             [100%]

=========================================================================================================================================================== ERRORS ===========================================================================================================================================================
_____________________________________________________________________________________________________________________________________________ ERROR at setup of test_no_scripts ______________________________________________________________________________________________________________________________________________

tmpdir_factory = TempdirFactory(_tmppath_factory=TempPathFactory(_given_basetemp=None, _trace=<pluggy._tracing.TagTracerSub object at 0x7f52bc183850>, _basetemp=PosixPath('/tmp/pytest-of-jon/pytest-6')))

    @pytest.fixture(scope='session')
    def wheels_and_eggs(tmpdir_factory):
        """Build wheels and eggs from test distributions."""
        test_distributions = "complex-dist", "simple.dist", "headers.dist"
        if sys.version_info >= (3, 6):
            # Only Python 3.6+ can handle packaging unicode file names reliably
            # across different platforms
            test_distributions += ("unicode.dist",)
    
        if sys.platform != 'win32':
            # ABI3 extensions don't really work on Windows
            test_distributions += ("abi3extension.dist",)
    
        pwd = os.path.abspath(os.curdir)
        this_dir = os.path.dirname(__file__)
        build_dir = tmpdir_factory.mktemp('build')
        dist_dir = tmpdir_factory.mktemp('dist')
        for dist in test_distributions:
            os.chdir(os.path.join(this_dir, 'testdata', dist))
>           subprocess.check_call([sys.executable, 'setup.py',
                                   'bdist_egg', '-b', str(build_dir), '-d', str(dist_dir),
                                   'bdist_wheel', '-b', str(build_dir), '-d', str(dist_dir)])

/home/jon/devel/wheel/tests/conftest.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', ...],), kwargs = {}, retcode = 1, cmd = ['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', ...]

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', '/tmp/pytest-of-jon/pytest-6/dist0', 'bdist_wheel', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', '/tmp/pytest-of-jon/pytest-6/dist0']' returned non-zero exit status 1.

/usr/lib64/python3.8/subprocess.py:364: CalledProcessError
--------------------------------------------------------------------------------------------------------------------------------------------------- Captured stdout setup ----------------------------------------------------------------------------------------------------------------------------------------------------
running bdist_egg
running egg_info
creating complex_dist.egg-info
writing complex_dist.egg-info/PKG-INFO
writing dependency_links to complex_dist.egg-info/dependency_links.txt
writing entry points to complex_dist.egg-info/entry_points.txt
writing requirements to complex_dist.egg-info/requires.txt
writing top-level names to complex_dist.egg-info/top_level.txt
writing manifest file 'complex_dist.egg-info/SOURCES.txt'
reading manifest file 'complex_dist.egg-info/SOURCES.txt'
writing manifest file 'complex_dist.egg-info/SOURCES.txt'
installing library code to /tmp/pytest-of-jon/pytest-6/build0
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/complexdist
copying complexdist/__init__.py -> build/lib/complexdist
creating /tmp/pytest-of-jon/pytest-6/build0/complexdist
copying build/lib/complexdist/__init__.py -> /tmp/pytest-of-jon/pytest-6/build0/complexdist
byte-compiling /tmp/pytest-of-jon/pytest-6/build0/complexdist/__init__.py to __init__.cpython-38.pyc
creating /tmp/pytest-of-jon/pytest-6/build0/EGG-INFO
copying complex_dist.egg-info/PKG-INFO -> /tmp/pytest-of-jon/pytest-6/build0/EGG-INFO
copying complex_dist.egg-info/SOURCES.txt -> /tmp/pytest-of-jon/pytest-6/build0/EGG-INFO
copying complex_dist.egg-info/dependency_links.txt -> /tmp/pytest-of-jon/pytest-6/build0/EGG-INFO
copying complex_dist.egg-info/entry_points.txt -> /tmp/pytest-of-jon/pytest-6/build0/EGG-INFO
copying complex_dist.egg-info/requires.txt -> /tmp/pytest-of-jon/pytest-6/build0/EGG-INFO
copying complex_dist.egg-info/top_level.txt -> /tmp/pytest-of-jon/pytest-6/build0/EGG-INFO
creating '/tmp/pytest-of-jon/pytest-6/dist0/complex_dist-0.1-py3.8.egg' and adding '/tmp/pytest-of-jon/pytest-6/build0' to it
removing '/tmp/pytest-of-jon/pytest-6/build0' (and everything under it)
running bdist_wheel
running build
installing to /tmp/pytest-of-jon/pytest-6/build0
running install
running install_lib
creating /tmp/pytest-of-jon/pytest-6/build0
creating /tmp/pytest-of-jon/pytest-6/build0/complexdist
copying build/lib/complexdist/__init__.py -> /tmp/pytest-of-jon/pytest-6/build0/complexdist
running install_egg_info
Copying complex_dist.egg-info to /tmp/pytest-of-jon/pytest-6/build0/complex_dist-0.1-py3.8.egg-info
running install_scripts
--------------------------------------------------------------------------------------------------------------------------------------------------- Captured stderr setup ----------------------------------------------------------------------------------------------------------------------------------------------------
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    setup(name='complex-dist',
  File "/home/jon/devel/wheel/.tox/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/jon/devel/wheel/.tox/py38/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 342, in run
    self.egg2dist(self.egginfo_dir, distinfo_dir)
  File "/home/jon/devel/wheel/.tox/py38/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 470, in egg2dist
    write_pkg_info(os.path.join(distinfo_path, 'METADATA'), pkg_info)
  File "/home/jon/devel/wheel/.tox/py38/lib/python3.8/site-packages/wheel/pkginfo.py", line 43, in write_pkg_info
    BytesGenerator(out, mangle_from_=False, maxheaderlen=0).flatten(message)
  File "/usr/lib64/python3.8/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/lib64/python3.8/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/lib64/python3.8/email/generator.py", line 214, in _dispatch
    meth(msg)
  File "/usr/lib64/python3.8/email/generator.py", line 432, in _handle_text
    super(BytesGenerator,self)._handle_text(msg)
  File "/usr/lib64/python3.8/email/generator.py", line 249, in _handle_text
    self._write_lines(payload)
  File "/usr/lib64/python3.8/email/generator.py", line 155, in _write_lines
    self.write(line)
  File "/usr/lib64/python3.8/email/generator.py", line 406, in write
    self._fp.write(s.encode('ascii', 'surrogateescape'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 29-31: ordinal not in range(128)
___________________________________________________________________________________________________________________________________________ ERROR at setup of test_unicode_record ____________________________________________________________________________________________________________________________________________

tmpdir_factory = TempdirFactory(_tmppath_factory=TempPathFactory(_given_basetemp=None, _trace=<pluggy._tracing.TagTracerSub object at 0x7f52bc183850>, _basetemp=PosixPath('/tmp/pytest-of-jon/pytest-6')))

    @pytest.fixture(scope='session')
    def wheels_and_eggs(tmpdir_factory):
        """Build wheels and eggs from test distributions."""
        test_distributions = "complex-dist", "simple.dist", "headers.dist"
        if sys.version_info >= (3, 6):
            # Only Python 3.6+ can handle packaging unicode file names reliably
            # across different platforms
            test_distributions += ("unicode.dist",)
    
        if sys.platform != 'win32':
            # ABI3 extensions don't really work on Windows
            test_distributions += ("abi3extension.dist",)
    
        pwd = os.path.abspath(os.curdir)
        this_dir = os.path.dirname(__file__)
        build_dir = tmpdir_factory.mktemp('build')
        dist_dir = tmpdir_factory.mktemp('dist')
        for dist in test_distributions:
            os.chdir(os.path.join(this_dir, 'testdata', dist))
>           subprocess.check_call([sys.executable, 'setup.py',
                                   'bdist_egg', '-b', str(build_dir), '-d', str(dist_dir),
                                   'bdist_wheel', '-b', str(build_dir), '-d', str(dist_dir)])

/home/jon/devel/wheel/tests/conftest.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', ...],), kwargs = {}, retcode = 1, cmd = ['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', ...]

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', '/tmp/pytest-of-jon/pytest-6/dist0', 'bdist_wheel', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', '/tmp/pytest-of-jon/pytest-6/dist0']' returned non-zero exit status 1.

/usr/lib64/python3.8/subprocess.py:364: CalledProcessError
_____________________________________________________________________________________________________________________________________________ ERROR at setup of test_convert_egg _____________________________________________________________________________________________________________________________________________

tmpdir_factory = TempdirFactory(_tmppath_factory=TempPathFactory(_given_basetemp=None, _trace=<pluggy._tracing.TagTracerSub object at 0x7f52bc183850>, _basetemp=PosixPath('/tmp/pytest-of-jon/pytest-6')))

    @pytest.fixture(scope='session')
    def wheels_and_eggs(tmpdir_factory):
        """Build wheels and eggs from test distributions."""
        test_distributions = "complex-dist", "simple.dist", "headers.dist"
        if sys.version_info >= (3, 6):
            # Only Python 3.6+ can handle packaging unicode file names reliably
            # across different platforms
            test_distributions += ("unicode.dist",)
    
        if sys.platform != 'win32':
            # ABI3 extensions don't really work on Windows
            test_distributions += ("abi3extension.dist",)
    
        pwd = os.path.abspath(os.curdir)
        this_dir = os.path.dirname(__file__)
        build_dir = tmpdir_factory.mktemp('build')
        dist_dir = tmpdir_factory.mktemp('dist')
        for dist in test_distributions:
            os.chdir(os.path.join(this_dir, 'testdata', dist))
>           subprocess.check_call([sys.executable, 'setup.py',
                                   'bdist_egg', '-b', str(build_dir), '-d', str(dist_dir),
                                   'bdist_wheel', '-b', str(build_dir), '-d', str(dist_dir)])

/home/jon/devel/wheel/tests/conftest.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', ...],), kwargs = {}, retcode = 1, cmd = ['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', ...]

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', '/tmp/pytest-of-jon/pytest-6/dist0', 'bdist_wheel', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', '/tmp/pytest-of-jon/pytest-6/dist0']' returned non-zero exit status 1.

/usr/lib64/python3.8/subprocess.py:364: CalledProcessError
_______________________________________________________________________________________________________________________________________________ ERROR at setup of test_unpack ________________________________________________________________________________________________________________________________________________

tmpdir_factory = TempdirFactory(_tmppath_factory=TempPathFactory(_given_basetemp=None, _trace=<pluggy._tracing.TagTracerSub object at 0x7f52bc183850>, _basetemp=PosixPath('/tmp/pytest-of-jon/pytest-6')))

    @pytest.fixture(scope='session')
    def wheels_and_eggs(tmpdir_factory):
        """Build wheels and eggs from test distributions."""
        test_distributions = "complex-dist", "simple.dist", "headers.dist"
        if sys.version_info >= (3, 6):
            # Only Python 3.6+ can handle packaging unicode file names reliably
            # across different platforms
            test_distributions += ("unicode.dist",)
    
        if sys.platform != 'win32':
            # ABI3 extensions don't really work on Windows
            test_distributions += ("abi3extension.dist",)
    
        pwd = os.path.abspath(os.curdir)
        this_dir = os.path.dirname(__file__)
        build_dir = tmpdir_factory.mktemp('build')
        dist_dir = tmpdir_factory.mktemp('dist')
        for dist in test_distributions:
            os.chdir(os.path.join(this_dir, 'testdata', dist))
>           subprocess.check_call([sys.executable, 'setup.py',
                                   'bdist_egg', '-b', str(build_dir), '-d', str(dist_dir),
                                   'bdist_wheel', '-b', str(build_dir), '-d', str(dist_dir)])

/home/jon/devel/wheel/tests/conftest.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', ...],), kwargs = {}, retcode = 1, cmd = ['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', ...]

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', '/tmp/pytest-of-jon/pytest-6/dist0', 'bdist_wheel', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', '/tmp/pytest-of-jon/pytest-6/dist0']' returned non-zero exit status 1.

/usr/lib64/python3.8/subprocess.py:364: CalledProcessError

----------- coverage: platform linux, python 3.8.3-final-0 -----------
Name                                                            Stmts   Miss  Cover   Missing
---------------------------------------------------------------------------------------------
.tox/py38/lib/python3.8/site-packages/wheel/__init__.py             1      0   100%
.tox/py38/lib/python3.8/site-packages/wheel/__main__.py            10     10     0%   5-19
.tox/py38/lib/python3.8/site-packages/wheel/bdist_wheel.py        268     48    82%   58-64, 73-93, 96-99, 112-114, 199-200, 211, 223, 252, 255, 271-272, 317-318, 333, 388-391, 437-445, 449-451
.tox/py38/lib/python3.8/site-packages/wheel/cli/__init__.py        56     43    23%   13-16, 24-25, 29-30, 34-35, 39-40, 44-73, 77-88
.tox/py38/lib/python3.8/site-packages/wheel/cli/convert.py        157    137    13%   31-34, 38-88, 124-159, 163-249, 254-269
.tox/py38/lib/python3.8/site-packages/wheel/cli/pack.py            49      3    94%   27, 29, 47
.tox/py38/lib/python3.8/site-packages/wheel/cli/unpack.py          12      7    42%   18-25
.tox/py38/lib/python3.8/site-packages/wheel/macosx_libfile.py     143      9    94%   232, 264-265, 275-276, 281, 286-288, 392
.tox/py38/lib/python3.8/site-packages/wheel/metadata.py            62      1    98%   34
.tox/py38/lib/python3.8/site-packages/wheel/pkginfo.py             29     14    52%   8, 13-25, 30-32
.tox/py38/lib/python3.8/site-packages/wheel/util.py                29      8    72%   7-14, 39, 46
.tox/py38/lib/python3.8/site-packages/wheel/wheelfile.py          112      1    99%   87
---------------------------------------------------------------------------------------------
TOTAL                                                             928    281    70%

================================================================================================================================================== short test summary info ===================================================================================================================================================
ERROR tests/test_bdist_wheel.py::test_no_scripts - subprocess.CalledProcessError: Command '['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', '/tmp/pytest-of-jon/pytest-6/dist0', 'bdist_wheel', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', ...
ERROR tests/test_bdist_wheel.py::test_unicode_record - subprocess.CalledProcessError: Command '['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', '/tmp/pytest-of-jon/pytest-6/dist0', 'bdist_wheel', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-...
ERROR tests/cli/test_convert.py::test_convert_egg - subprocess.CalledProcessError: Command '['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', '/tmp/pytest-of-jon/pytest-6/dist0', 'bdist_wheel', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d',...
ERROR tests/cli/test_unpack.py::test_unpack - subprocess.CalledProcessError: Command '['/home/jon/devel/wheel/.tox/py38/bin/python', 'setup.py', 'bdist_egg', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', '/tmp/pytest-of-jon/pytest-6/dist0', 'bdist_wheel', '-b', '/tmp/pytest-of-jon/pytest-6/build0', '-d', '/tmp...
========================================================================================================================================== 53 passed, 2 skipped, 4 errors in 6.91s ===========================================================================================================================================
ERROR: InvocationError for command /home/jon/devel/wheel/.tox/py38/bin/python -b -m pytest -W always (exited with code 1)
__________________________________________________________________________________________________________________________________________________________ summary ___________________________________________________________________________________________________________________________________________________________
ERROR:   py38: commands failed
```

**Comment by dholth** [comment]
We had to handle Unicode with Python 3.2's e-mail module. I think the modern e-mail module is also about smuggling binary into text by using surrogates, but don't quote me on that. The modern e-mail module is much more tuned for this sort of thing, with Policy objects to support file formats that are similar to rfc822 e-mail.

When you're bdist_wheel your main concern is round-tripping and it is not necessary to decode the fields into proper unicode strings.

A recent attempt using the Python 3.3+ email module: https://github.com/dholth/wgc/blob/master/wheelfile.py#L154

**Pull request closed without merging**
