### PR TITLE
Write the RECORD file as CSV

### PR DESCRIPTION
**Pull request by pfmoore**

### CODE REVIEW

**Comment by pfmoore** [comment]
Some tests fail on Windows, but the same tests seem to fail on master as well, so I'm assuming that's expected. No CI for Windows?

**Comment by agronholm** [comment]
> Some tests fail on Windows, but the same tests seem to fail on master as well, so I'm assuming that's expected. No CI for Windows?

Azure Pipelines is the only reasonable way we could have a Windows CI. I will look into that when time permits.

**Comment by agronholm** [comment]
Thank you. I had actually implemented this fix on my own too but was stuck making the tests pass on Python 2. This version was somewhat simpler than mine.

**Comment by agronholm** [comment]
> Azure Pipelines is the only reasonable way we could have a Windows CI. I will look into that when time permits.

Actually, I forgot about this: https://blog.travis-ci.com/2018-10-11-windows-early-release

**Pull request merged**
