### PR TITLE
Minor code cleanup.

### PR DESCRIPTION
**Pull request by RDIL**
List of changes:
* Adds a little bit of in-code documentation to help future contributors understand what is going on.
* gitignored mypy caches, because my IDE ran it automatically
* Fixed some typos
* Inlined a minor function that my python interpreter was failing to import for some reason

Signed-off-by: Reece Dunham <me@rdil.rocks>

### CODE REVIEW

**Comment by RDIL** [comment]
@agronholm review ping :)

**Comment by agronholm** [comment]
One thing that caught my eye: the headlines in function docstrings should be in imperative form, like "Do a thing" rather than "Does a thing".

Are you in a hurry to get this merged?

**Comment by RDIL** [comment]
No, just want to move it along.  Fixing now.

**Comment by agronholm** [comment]
The library is now going through some major changes due to readying the public API, dropping of Python 2 support and moving the bdist_wheel command to setuptools. That's why I may end up dropping this PR.

**Comment by agronholm** [comment]
The `publicapi` branch is the future of wheel, and the code layout has already changed significantly and has made this PR incompatible. Sorry.

**Pull request closed without merging**
